### ISSUE TITLE
No return_clim keyword in calc_anomaly

### ISSUE THREAD

**Issue by sebhahn** [TUW-GEO/pytesmo#110]
There is no `return_clim` keyword in `calc_anomaly` in the [definition](https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/time_series/anomaly.py#L11) but used [here](https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/time_series/plotting.py#L128) as parameter.

**Comment by tracyscanlon** [comment]
The return_clim keyword is available in calc_anomaly
