### ISSUE TITLE
numpy issue with timedate.doy

### ISSUE THREAD

**Issue by alegrub88** [TUW-GEO/pytesmo#123]
After an update of numpy, timedate.doy didn't work any more because of the addition of a boolean type array to an integer array (Line 306)... I could resolve it by a simple type conversion:

day_of_year = day_of_year - nonleap_years.astype('int') + \
            np.logical_and(day_of_year < 60, nonleap_years).astype('int')

Not sure if this was really a numpy issue or something else, but this made it work again.

**Comment by cpaulik** [comment]
Which version of numpy are you using. I just tried with 1.13.1 and it still works like it should. 

But a conversion to integer is probably a good idea anyway.

**Comment by cpaulik** [comment]
I've opened #125 to add tests for the doy function which where missing. Could you try to write a test that shows the problem you experienced?

**Comment by alegrub88** [comment]
It's numpy version 1.13.3 ... pretty much any call should cause this error, because the boolean arrays are created inside.

**Comment by cpaulik** [comment]
It does not for me:

The most basic example:

```
import numpy as np
print np.__version__
a = np.array([1, 1, 1], dtype=int)
b = np.array([True, False, False], dtype=bool)
print a + b
```
gives the output:

```
1.13.3
[2 1 1]
```

I'll come to your office.

**Comment by cpaulik** [comment]
The problem was that another function did give pandas Int64Index objects to this function which do not support int+bool addition. Should be fixed in the next release.
