### ISSUE TITLE
nan values for estimated error from approach 2 triple collocation/pytesmo

### ISSUE THREAD

**Issue by AmenehTavakol** [TUW-GEO/pytesmo#130]
Hi,
I have 3 sets of data and i run both codes on them:
**Approach 1**: pytesmo.scaling( ) and pytesmo.metrics.tcol_error( ) 
                          It return 3 values (ex,ey,ez)
**Approach 2**: pytesmo.metrics.tcol_snr( ), 
                          It returns 9 values (first 3: SNR, second 3: (ex,ey,ez) and third 3: beta)

From approach 2, I received some "nan" as a result for SNR and the same for error (60 "nan" for 60 days out of 950 days). I assume the amount of error should be very low or negative. How can I cope with this problem?  
Did anybody experience the same problem?

**Comment by cpaulik** [comment]
As written by @alegrub88 via email:


> Due to estimation uncertainties (or violated assumptions) error variance estimates might become negative. Since the square root is taken (i.e. error standard deviations are calculated) before they are returned, return values become NaN in such case. 
> 
> The "tcol_error" routine avoids this by taking the absolute value before taking the square root, which the "tcol_snr" routine doesn't. 
> 
> I always take the absolute value, but you don't have to if you feel uncomfortable doing so (which some people do)... A discussion on that is provided here:
> http://onlinelibrary.wiley.com/doi/10.1002/2017WR021277/full
> 
> In my experience this happens only very rarely anyway.
> 
> Hope this helps!
