### ISSUE TITLE
Fix issues related to pandas 0.23

### ISSUE THREAD

**Issue by sebhahn** [TUW-GEO/pytesmo#136]
Some tests are failing because pandas 0.23 is more restrictive, I think it shouldn't be a lot of effort to fix them.

https://pandas.pydata.org/pandas-docs/stable/whatsnew.html

**Comment by cpaulik** [comment]
Yes we should fix them. Did you check which change exactly broke pytesmo?

**Comment by sebhahn** [comment]
Not yet, but @mazweg fixed one of the errors for the ismn package https://github.com/TUW-GEO/ismn/commit/67e318a3ae845548fe3add588a64db0eb65dffe5

**Comment by awst-baum** [comment]
I've tried my hand at this but it's not quite clear to me what change in pandas brought the problems about. See my description in the pull request.
