### ISSUE TITLE
ISMN reader produces different indices for same stations on different systems

### ISSUE THREAD

**Issue by awst-baum** [TUW-GEO/pytesmo#143]
Like it says in the title: The ISMN reader (in particular `get_dataset_ids`) produces different indices for the same stations on different systems. This makes it harder to check errors occurring in a production system on your developer machine.

I think this comes from the metadata collector (pytesmo.io.ismn.metadata_collector.collect_from_folder) line 57, which uses `os.walk`. `os.walk` doesn't guarantee an order but we could sort the folders and files lists to alphabetical order. This would take care of the problem, barring locale issues (different sorting order from different locales).

**Comment by cpaulik** [comment]
All ismn related improvements should go into https://github.com/TUW-GEO/ismn . The ISMN readers will be removed from pytesmo. See also https://github.com/TUW-GEO/pytesmo/pull/124

**Comment by awst-baum** [comment]
Hm, I'm confused about that - it seems you've been planning to remove the ISMN reader from pytesmo for about a year now but it got stuck because the relevant branch is still unmerged? What's missing to complete the merge?

**Comment by cpaulik** [comment]
It was just not a priority. As it stands now we will have to rebase the branch and do some checks if everything was removed. I'll look into that when I have time.
