### ISSUE TITLE
Build fails because of basemap import in ismn test

### ISSUE THREAD

**Issue by awst-baum** [TUW-GEO/pytesmo#153]
It looks like the Travis build fails because tests `tests/test_ismn/test_interface.py` and `tests/test_validation_framwork/test_validation.py` fail.

They fail because of an issue with the basemap import in `pytesmo/io/ismn/interface.py:44`: `E   KeyError: 'PROJ_LIB'`

Should the tests remain in pytesmo or should they be moved to the ismn repos?
If they remains in pytesmo, shouldn't they (and all other tests and pytesmo code) be updated to use the ismn library?

@cpaulik Do you already have those changes lined up somewhere or can someone else look at this? (I'm currently too busy with the preparations for the QA4SM workshop but that may ease up at the end of the month.)

**Comment by cpaulik** [comment]
It was planned to remove the ismn from pytesmo. https://github.com/TUW-GEO/pytesmo/pull/124 should have most of the necessary changes. 

But the validation test will probably remain and use the ismn package.

**Comment by sebhahn** [comment]
@wpreimes this is also obsolete right_

**Comment by wpreimes** [comment]
Yes, the Ismn package uses cartopy now.
