### ISSUE TITLE
TC metrics calculators

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/pytesmo#154]
Triple Collocation is not yet implemented in the master branch validation framework. There is a branch (add-tc-metrics-calc) that adds the metrics calculators for TC and seasonal basic metrics. @cpaulik did you finish this? As far as I tested it, it should work. Do you remember if something was missing or what you intended to do next?

**Comment by cpaulik** [comment]
I've just opened a MR for the `add-tc-metrics-calc` in https://github.com/TUW-GEO/pytesmo/pull/155/files

But I do not see any TC metrics there. 

As far as I remember there are already TC `metricCalculators` in an internal project of TU Wien and we wanted to open source them in this branch

**Comment by wpreimes** [comment]
The HSAF calculator has some in it

**Comment by cpaulik** [comment]
Yes. I've overlooked that.

Do you need more than what is in this branch?

**Comment by wpreimes** [comment]
I think for now we are happy if we can use that :) Thanks

________________________________
Von: Christoph Paulik <notifications@github.com>
Gesendet: Mittwoch, 16. Januar 2019 16:00
An: TUW-GEO/pytesmo
Cc: Preimesberger, Wolfgang; Author
Betreff: Re: [TUW-GEO/pytesmo] TC metrics calculators (#154)


Yes. I've overlooked that.

Do you need more than what is in this branch?

-

**Comment by sebhahn** [comment]
@wpreimes this is now implement, correct?

**Comment by wpreimes** [comment]
Yes
