### ISSUE TITLE
Move resample code to repurpose

### ISSUE THREAD

**Issue by sebhahn** [TUW-GEO/pytesmo#166]
Move resample code to repurpose

https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/grid/resample.py

**Comment by wpreimes** [comment]
We can now delete it from pytesmo

**Comment by cpaulik** [comment]
We should wait a few releases before deleting it outright. Normally the moved code is imported from repurpose and a deprecation warning is added. As to not break code that still imports from pytesmo.

**Comment by wpreimes** [comment]
Good point, I will do it like this
