### ISSUE TITLE
Move dekad functions

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/pytesmo#195]
Functions from ``timedate.dekad`` dont really fit into pytesmo I think. Maybe move them to https://github.com/TUW-GEO/cadati (@sebhahn) ? Or to the CCI processor where they are actually used (@tracyscanlon)?

**Comment by sebhahn** [comment]
should be moved to cadati, because they are used in other processing chains as well

**Comment by wpreimes** [comment]
Ok I will open a PR there
