### ISSUE TITLE
need cftime==1.0.4.2

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/pytesmo#199]
Temporal matching can fail when using the ``cftime>=1.1.0`` because of incompatible data types during temporal matching ``types dtype('O') and dtype('<M8[ns]')``. This could also be a data issue and might not be related directly to pytesmo.
Needs some more investigation, probably in #176 

Currently pinning ``cftime==1.0.4.2`` fixes this in QA4SM

**Comment by awst-baum** [comment]
`dtype('O')` means `cftime.DatetimeGregorian` in this case, which is compared against `datetime64` `-> dtype('<M8[ns]')`. In our case it was C3S data that got DatetimeGregorian indices during read, while ISMN data has datetime64. The line in question is `pytesmo.temporal_matching.df_match:59`: `comp_step = arg.index.values - reference.index.values[0]`

**Comment by cpaulik** [comment]
At first glance this looks like a issue in the C3S data reader. The pytesmo interface needs a pandas dataframe with a datetime index. 

I think Sebastian was solving something similar a few weeks ago. There should be a keyword in the netcdf4 package for the return type of datetime variables

**Comment by awst-baum** [comment]
> At first glance this looks like a issue in the C3S data reader. 

C3S uses `GriddedNcTs` to do the reading, so all other readers using the same base class may also be affected. I think the magic is (not) happening in `time_series.GriddedNcTs._read_gp`

> The pytesmo interface needs a pandas dataframe with a datetime index.

Yeah, we are aware, we just didn't know how to get it one ;)

> I think Sebastian was solving something similar a few weeks ago. There should be a keyword in the netcdf4 package for the return type of datetime variables

An easy fix would be just the thing :D

**Comment by sebhahn** [comment]
here is what we've changed for `pynetcf` when calling `netCDF4.num2date`

https://github.com/TUW-GEO/pynetcf/commit/a7ee3a90ddab5da5ab4214e4012b4f944b5d18b8
