### ISSUE TITLE
Update CDF matching

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/pytesmo#203]
There are some updates to CDF matching available (by @Lmoesinger for VODCA, and implemented in CCI by @tracyscanlon ) which could be used in pytesmo as well.

**Comment by teije01** [comment]
Out of interest, may I ask what is in these suggested updates?

**Comment by tracyscanlon** [comment]
The new CDF matching technique would implement a combination of piecewise linear interpolation and linear least-squares regression. A full description of the method to be implemented can be found in Moesinger et al. (2020), section 3.2 - https://essd.copernicus.org/articles/12/177/2020/essd-12-177-2020-discussion.html. Please let us or the main author (@Lmoesinger) know if you have any questions on this method.

**Comment by s-scherrer** [comment]
closed via #207
