### ISSUE TITLE
dropduplicates=True only drops duplicates in non-ref in df_match

### ISSUE THREAD

**Issue by s-scherrer** [TUW-GEO/pytesmo#218]
When trying to replace `df_match` with the new implementation `temporal_collocation` in `BasicTemporalMatcher` I encountered a strange issue with `dropduplicates`, namely that only duplicates in the non-reference frame will be dropped (see example). Is this the intended behaviour, @wpreimes @sebhahn ?

```
index1 = pd.date_range("2000-01-01", "2000-01-05", freq="D")
index2 = pd.date_range("2000-01-01 03:00", "2000-01-05 03:00", freq="D")
index1.values[2] = index1.values[3]
df1 = pd.DataFrame({"k1": np.arange(len(index1))}, index=index1)
df2 = pd.DataFrame({"k2": np.arange(len(index2))}, index=index2)
```
The dataframes look like this:
```
In [28]: df1
Out[28]: 
            k1
2000-01-01   0
2000-01-02   1
2000-01-04   2
2000-01-04   3
2000-01-05   4

In [29]: df2
Out[29]: 
                     k2
2000-01-01 03:00:00   0
2000-01-02 03:00:00   1
2000-01-03 03:00:00   2
2000-01-04 03:00:00   3
2000-01-05 03:00:00   4
```

When using the frame with duplicates in the index I get the following result:
```
In [32]: df_match(df1, df2, dropduplicates=True)
Out[32]: 
            distance  k2               index
2000-01-01     0.125   0 2000-01-01 03:00:00
2000-01-02     0.125   1 2000-01-02 03:00:00
2000-01-04     0.125   3 2000-01-04 03:00:00
2000-01-04     0.125   3 2000-01-04 03:00:00
2000-01-05     0.125   4 2000-01-05 03:00:00
```
The 2000-01-04 entry is duplicated in the results, which is not really what I would expect from the docstring when using `dropduplicates=True`:
```
    dropduplicates : boolean
        Drop duplicated temporal matched (default: False)
```

**Comment by sebhahn** [comment]
Could you please point/link to the version/commit of df_match you are referring to?

**Comment by s-scherrer** [comment]
I'm referring to the current master branch.

**Comment by sebhahn** [comment]
Did you set `dropduplicates` to True? If it is False nothing is changed in the result

**Comment by s-scherrer** [comment]
Yes:

```
In [32]: df_match(df1, df2, dropduplicates=True)
Out[32]: 
            distance  k2               index
2000-01-01     0.125   0 2000-01-01 03:00:00
2000-01-02     0.125   1 2000-01-02 03:00:00
2000-01-04     0.125   3 2000-01-04 03:00:00
2000-01-04     0.125   3 2000-01-04 03:00:00
2000-01-05     0.125   4 2000-01-05 03:00:00
```
In this example `df1` has a duplicated index, which leads to a duplication of entry 3 in the matched dataframe.

**Comment by sebhahn** [comment]
My best guess why this fails is that the distance is the same for the duplicated entry

**Comment by s-scherrer** [comment]
But what would be the intended behaviour? Should it drop the duplicated index from the reference dataframe?

**Comment by sebhahn** [comment]
Yes and keep the temporal neighbor with the minimum distance

**Comment by s-scherrer** [comment]
Ok, that's in line with how the new `temporal_collocation` function works. I will just need to change the tests a bit, because some of the ASCAT data has duplicated indices.

**Comment by sebhahn** [comment]
These duplicates are there by mistake, but the temporal collocation function should probably make the user aware if this is the case
