### ISSUE TITLE
ismn package should not be an installation dependency

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/pytesmo#238]
Hi,

We ran into some dependency issue recently and noticed that `pytesmo` causes us to install `ismn`. 

The `ismn` package is only used in [this test](https://github.com/TUW-GEO/pytesmo/blob/8f6af4a115bd771ecee1eff65e69bcc495a18c2a/tests/test_validation_framework/test_validation.py#L62) as far as I can tell.

Could we make this a test dependency or at least optional?

**Comment by teije01** [comment]
The dependency issue we got is this one: https://github.com/TUW-GEO/ismn/issues/36

**Comment by wpreimes** [comment]
Thanks, yes, I think we should make it optional @s-scherrer

**Comment by s-scherrer** [comment]
Should be fixed by #239. If all goes well, the CI should upload the new package to PyPI in a few minutes. Can you let us know if this solved your issues, @cpaulik @teije01 ?

**Comment by teije01** [comment]
Yes, this indeed solves our issue. Thanks for the quick response

**Comment by cpaulik** [comment]
Thank you also from my side. That was exceptionally quick
