### ISSUE TITLE
Skip Triple Collocation CIs when not enough data is available instead of raising Error

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/pytesmo#251]
Metrics Operator for TC metrics with CI raises an error when less than 100 observations (default) are available https://github.com/TUW-GEO/pytesmo/blob/master/src/pytesmo/validation_framework/metric_calculators.py#L1740

I think it would make more sense if in those cases the CIs are skipped (e.g. NaN) but the TC results are still returned. @s-scherrer @pstradio @sheenaze?

**Comment by sheenaze** [comment]
Does it make sense to return only TC? Wouldn't be an inconsistency? I mean... you're the one who knows it better, the most important thing is to handle it, so it doesn't crash the entire celery job.

**Comment by s-scherrer** [comment]
Closed via #256
