### ISSUE TITLE
Implement improvements in CDF matching

### ISSUE THREAD

**Issue by s-scherrer** [TUW-GEO/pytesmo#255]
Recently, @pstradio and I found a few issues with the CDF matching implementation in pytesmo:
- sorting the data before [this line](https://github.com/TUW-GEO/pytesmo/blob/f1e4518537076b76609e8e360294f0eb504292c2/src/pytesmo/utils.py#L337) greatly improves performance
- there's a small bug that can lead to strong outliers in the linear edge scaling: https://github.com/TUW-GEO/pytesmo/blob/f1e4518537076b76609e8e360294f0eb504292c2/src/pytesmo/utils.py#L348

Additionally, I would like to make the CDF matching implementation in pytesmo a bit more flexible, and provide the option for separate CDF parameter calculation and transformation (while keeping the current interface as it is). I think it would also be good to get some input from other people who use the Moesinger et al. 2020 method but use a different implementation, to find out what requirements they have and what is preventing them from using pytesmo at the moment. @wpreimes do you have an overview of who is using a different implementation than the one in pytesmo?

**Comment by wpreimes** [comment]
sorry, I don't really now about other implementation. CCI uses a different one. I would try to implement everything in pytesmo and then use pytesmo in CCI (also the inner-annual / dynamic method for example).
