### ISSUE TITLE
data_manager drops na values

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/pytesmo#49]
the data_manager drops the na values during reading. 
This can be dangerous if the dataframe contains several columns of which only one column has a na value. So we should either change this to `dropna(how='all')` or remove it completely and let the data reader or data preparation take care of it.

@aplocon Is there any other reason you can think of why it would make sense to drop the nan values in https://github.com/TUW-GEO/pytesmo/blob/develop/pytesmo/validation_framework/data_manager.py#L159 or https://github.com/TUW-GEO/pytesmo/blob/develop/pytesmo/validation_framework/data_manager.py#L209

**Comment by aplocon** [comment]
You are right, this should be completely removed.
