### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by sebhahn** [TUW-GEO/pytesmo#88]
The data manager of the validation framework catches only IOErrors, but e.g. the netcdf4 raises a RuntimeError in case file doesn't exist see [here](https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/validation_framework/data_manager.py#L183).

Solution would be capturing also a RuntimeError

e.g.
`except (RuntimeError, IOError) as err:`

**Comment by cpaulik** [comment]
I've raised this at https://github.com/Unidata/netcdf4-python/issues/546 so it might be fixed. But in the meantime we can add an except for the RuntimeError but reraise it if the message is not `No such file or directory`. Otherwise we would hide too many possible failure scenarios.

**Comment by sebhahn** [comment]
Sounds ok for me!
